### PR TITLE
Update dynamicport.md

### PR DESCRIPTION
**Pull request by DolorHunter**
Add inbounds and outbounds to make config completed

### CODE REVIEW

**Comment by kslr** [comment]
Recommend removing all update history

**Comment by DolorHunter** [comment]
> Recommend removing all update history

All history has been removed

**Comment by kslr** [comment]
Okay, I mean the whole section

**Comment by DolorHunter** [comment]
> 
> 
> Okay, I mean the whole section

It's removed in the third commit. I've double-checked for it.

**Pull request merged**
